//! Reputation NFT contract.
//!
//! ## Design
//!
//! `ReputationNftContract` is a minimal, purpose-built contract that tracks a
//! per-address reputation score (u32).  It is intentionally separate from the
//! lending contract so that:
//!
//! 1. The lending contract can be upgraded without resetting reputation data.
//! 2. A single reputation contract can potentially service multiple lending
//!    contracts.
//! 3. The contract can be audited and deployed independently.
//!
//! ## Dynamic Yield & `calculate_dynamic_yield`
//!
//! The previous codebase referenced a `calculate_dynamic_yield` function that
//! depended on `ReputationNftExternalClient`.  That function was removed because
//! it depended on a contract that only existed under `#[cfg(test)]`, making it
//! untestable in production.
//!
//! Instead, **yield is now a two-layer system**:
//!
//! - **Static yield** (`total_yield`): locked in at disbursement time from
//!   `Config::yield_bps`.  Vouchers always receive this.
//! - **Compound interest** (`accrued_interest`): computed daily on the
//!   outstanding principal (see `helpers::calculate_daily_compound_interest`).
//!   This replaces "dynamic yield" — it is deterministic and fully on-chain
//!   without any external oracle call.
//!
//! Reputation score (from this contract) can still be read by UIs via
//! `QuorumCreditContract::get_reputation()`, and admins can choose to offer
//! better loan terms off-chain based on reputation history.  On-chain dynamic
//! yield adjustment based on reputation is a future roadmap item that would
//! require a governance vote to update `Config::yield_bps` per borrower.

#![allow(unused)]

use soroban_sdk::{contract, contractclient, contractimpl, contracttype, Address, Env};

#[contracttype]
pub enum RepKey {
    Minter,         // Address authorised to mint/burn (the main lending contract)
    Score(Address), // borrower → u32 reputation score
}

/// External client trait — generated by `#[contractclient]` for cross-contract calls.
/// The lending contract uses `ReputationNftExternalClient` to call this contract.
#[contractclient(name = "ReputationNftExternalClient")]
pub trait ReputationNftContractTrait {
    fn initialize(env: Env, minter: Address);
    fn mint(env: Env, to: Address);
    fn burn(env: Env, from: Address);
    fn balance(env: Env, addr: Address) -> u32;
}

/// Production reputation NFT contract.
///
/// Deploy this contract separately and call `set_reputation_nft` on the lending
/// contract to wire it up.  The `minter` registered here must be the lending
/// contract address.
#[contract]
pub struct ReputationNftContract;

#[contractimpl]
impl ReputationNftContract {
    /// One-time setup: record the authorised minter (the lending contract).
    pub fn initialize(env: Env, minter: Address) {
        assert!(
            !env.storage().instance().has(&RepKey::Minter),
            "already initialized"
        );
        env.storage().instance().set(&RepKey::Minter, &minter);
    }

    /// Mint one reputation point to `to`. Only callable by the registered minter.
    pub fn mint(env: Env, to: Address) {
        let minter: Address = env
            .storage()
            .instance()
            .get(&RepKey::Minter)
            .expect("not initialized");
        minter.require_auth();

        let score: u32 = env
            .storage()
            .persistent()
            .get(&RepKey::Score(to.clone()))
            .unwrap_or(0);
        env.storage()
            .persistent()
            .set(&RepKey::Score(to), &(score + 1));
    }

    /// Burn one reputation point from `from` (floor at 0). Only callable by the registered minter.
    pub fn burn(env: Env, from: Address) {
        let minter: Address = env
            .storage()
            .instance()
            .get(&RepKey::Minter)
            .expect("not initialized");
        minter.require_auth();

        let score: u32 = env
            .storage()
            .persistent()
            .get(&RepKey::Score(from.clone()))
            .unwrap_or(0);
        env.storage()
            .persistent()
            .set(&RepKey::Score(from), &score.saturating_sub(1));
    }

    /// Returns the reputation score for `addr`.
    pub fn balance(env: Env, addr: Address) -> u32 {
        env.storage()
            .persistent()
            .get(&RepKey::Score(addr))
            .unwrap_or(0)
    }
}

// ── Test helpers ──────────────────────────────────────────────────────────────
//
// The `ReputationNftContractClient` used in integration tests is auto-generated
// by `#[contractimpl]` above (available under `testutils` feature).  Tests can
// register `ReputationNftContract` directly:
//
//   let nft_id = env.register_contract(None, ReputationNftContract);
//
// No additional test-only wrapper is required.
